wip: inline staking
TalismanSociety/talisman pull request #1585
Opened 2024-08-15 14:24 UTC by 0xKheops

2024-09-08 13:21 UTC, chidg commented on apps/extension/src/ui/domains/Staking/useStakingBanner.tsx
> +      else result = false
`result` is already false

2024-09-08 13:34 UTC, chidg commented on apps/extension/src/ui/domains/Staking/NomPoolBond/useNomPoolBondWizard.ts
> +      return t("An account cannot do both regular staking and nomination pool staking")
Requested by Toby: can we make the element containing this message a bit smaller to make it break more evenly? Or add a line break half way through the message?

2024-09-08 13:34 UTC, chidg requested changes
It's very beautiful!
Couple of small changes/comments.

2024-09-09 01:25 UTC, 0xKheops commented on apps/extension/src/ui/domains/Staking/useStakingBanner.tsx
> +      else result = false
true!

2024-09-09 11:50 UTC, chidg approved these changes
LGTM!

2024-09-10 00:02 UTC, merged