feat: ✨ batch import accounts
TalismanSociety/talisman pull request #866
Opened 2023-06-22 03:16 UTC by 0xKheops

- Closes #865 

Progress : 
- [x] Account picker
- [x] Unlock multiple accounts at once
- [x] Import single or multi
- [x] Prevent importing external/hardware accounts (cuz we don't know the origin)
- [x] New file picker
- [x] Display balances in account picker
- [x] Live update progress bar when trying passwords
- [x] QA
- [x] Cleanup

2023-07-07 08:11 UTC, chidg requested changes
Great code and UI
Few small points
- I'm not 100% happy with the 'input password for multiple accounts' modal UX. It doesn't feel totally clear what's going on. I suggested a minor copy change, and I think we should release and get user feedback. When we initially discussed this I imagined a UI where the password input took place in the context of the account list, so that it was more clear that the passwords were for the individual accounts. Anyway, let's release this and see
- Some validation on JSON upload would be good. Can we validate that the shape of the json data is correct? Currently you can load any random json file and the page will not display any error message.
- When a file is loaded where all of its accounts are already imported, maybe we should have a special message like "No importable accounts present"
![Screenshot 2023-07-07 at 3 36 02 pm](https://github.com/TalismanSociety/talisman/assets/3326734/75faf519-e607-437a-b68f-e48467eb5b73)
- Can we have a tooltip on the locked/unlocked icon in the accounts list - I wasn't totally clear what that meant the first time I tried.
![Screenshot 2023-07-07 at 11 24 43 am](https://github.com/TalismanSociety/talisman/assets/3326734/d3e9149e-6037-4d95-98e0-dbe3a337a35f)

2023-07-07 08:11 UTC, chidg commented on apps/extension/src/ui/apps/dashboard/routes/AccountAddJson/UnlockJsonAccountsButton.tsx
> +            {t("Enter passwords until all selected accounts are unlocked")}
Maybe `Enter the passwords for each of your selected accounts, until all accounts unlocked`.

2023-07-09 08:25 UTC, 0xKheops commented
Implemented an alert like this if all importable accounts are already in the keyring

![image](https://github.com/TalismanSociety/talisman/assets/26880866/18c9a387-4c2c-47f2-ad53-02ade7a84693)

2023-07-10 00:36 UTC, chidg approved these changes
LGTM!

2023-07-10 00:37 UTC, merged